name: aplc_optimization
channels:
  - defaults
  - conda-forge
  - gurobi
  - http://ssb.stsci.edu/astroconda
dependencies:
  - gurobi
  - jupyter
  - matplotlib
  - memory_profiler
  - pip
  - python=3.8
  - sphinx
  - sphinx-automodapi
  - sphinx_rtd_theme
  - pip:
    - asdf
    - gurobipy
    - hcipy
    - poppy
    - stsci-rtd-theme